# Generated by Django 6.0.4 on 2026-04-24 16:19

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_email_alter_user_email_verification_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DoseTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=1, max_digits=5)),
                ('unit', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('ML', 'Milliliter')], max_length=10)),
                ('days_of_week', models.JSONField(default=api.models.default_days_of_week)),
                ('regimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose_times', to='api.regimen')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
        migrations.CreateModel(
            name='RegimenMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('form', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup')], max_length=10)),
                ('strength', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='regimen',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.regimenmedicine'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('ML', 'Milliliter')], max_length=10)),
                ('low_stock_threshold_days', models.IntegerField(default=3)),
                ('reorder_url', models.URLField(blank=True, default='')),
                ('last_low_stock_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_reorder_response', models.CharField(blank=True, max_length=10, null=True)),
                ('last_reorder_response_at', models.DateTimeField(blank=True, null=True)),
                ('regimen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='api.regimen')),
            ],
        ),
        migrations.CreateModel(
            name='IntakeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('TAKEN', 'Taken'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=10)),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('unit', models.CharField(blank=True, choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('ML', 'Milliliter')], max_length=10, null=True)),
                ('dose_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dosetime')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('regimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_logs', to='api.regimen')),
            ],
            options={
                'ordering': ['-date', 'dose_time__time'],
                'unique_together': {('regimen', 'dose_time', 'date')},
            },
        ),
    ]
