# Generated by Django 6.0.4 on 2026-04-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_regimen_dosetime_regimenmedicine_regimen_medicine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intakelog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('TAKEN', 'Taken'), ('SKIPPED', 'Skipped'), ('MISSED', 'Missed')], default='PENDING', max_length=10),
        ),
    ]
