# Generated by Django 6.0.4 on 2026-04-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='regimenmedicine',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='regimenmedicine',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='regimenmedicine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='medicines/'),
        ),
        migrations.AddIndex(
            model_name='regimenmedicine',
            index=models.Index(fields=['user', 'name'], name='api_regimen_user_id_b0d392_idx'),
        ),
    ]
