# Generated by Django 6.0.4 on 2026-05-04 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_profile_caregiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='caregiver',
            name='expo_push_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('MISSED_DOSE', 'Missed Dose'), ('LOW_STOCK', 'Low Stock'), ('WEEKLY_REPORT', 'Weekly Report'), ('DOSE_REMINDER', 'Dose Reminder')], max_length=20)),
                ('channel', models.CharField(choices=[('PUSH', 'Push Notification'), ('EMAIL', 'Email')], max_length=10)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='PENDING', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('caregiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='api.caregiver')),
                ('intake_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='api.intakelog')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['patient', 'notification_type'], name='api_notific_patient_345433_idx'), models.Index(fields=['caregiver', 'sent_at'], name='api_notific_caregiv_726e38_idx')],
            },
        ),
    ]
